project:
  type: website
  output-dir: docs
  
format:
  html:
    code-fold: true
    fig-asp: 0.8
    fig-width: 8

execute:
  echo: false

website:
  title: "BJJ Absolute Class Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Intro
      - href: Overview.qmd
        text: Overview
      - href: Placing_Analysis.qmd
        text: Placing Analysis
      - href: Tournament_Analysis.qmd
        text: Tournament Analysis
      - href: Time_Series_Analysis.qmd
        text: Time Series Analysis
      - href: Data_Details.qmd
        text: Data Details
      - href: Conclusion.qmd
        text: Conclusion
      - href: About_Me.qmd
        text: About Me
    right:
      - icon: github
        href: https://github.com/GrantWooley/BJJ-Absolute-Class-Analysis/tree/master
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/grantwooley/
        aria-label: Linkedin