project:
  type: website
  output-dir: docs

website:
  title: "BJJ Absolute Class Analysis"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: pageOne.qmd
        text: Page One