project:
  type: website
  output-dir: docs

website:
  title: "BJJ Absolute Class Analysis"
  navbar:
    left:
      - href: Overview.qmd
        text: Overview
      - href: Placing_Analysis.qmd
        text: Placing Analysis
