---
title: "BJJ Absolute Class Analysis"
---

This project aims to determine using data what weight a competitor needs to be to have realistic chance of winning the Absolute class at major IBJJF BJJ tournament.

```{r}
#| message: false
#| warning: false
#| include: false
library(tidyverse)
library(data.table)

```

```{r}
#| include: false
Path_Data <- file.path("C:/Users/grant/OneDrive/Road To DE/Data Projects/BJJ Absolute Class Analysis/data")
File_Absolute_Results <- "IBJJF_Results_Absolute.rds"
File_Results <- "IBJJF_Results_Weight_Class.rds"
dt_Results <- readRDS(file.path(Path_Data,File_Results))
dt_Absolute_Results <- readRDS(file.path(Path_Data,File_Absolute_Results))


```

# Simple Distribution

From the start graphing a simple distribution we see there is a trend that competitors in the heavier weight classes reach the podium more often.

```{r}
#| echo: false
Factor_Order <- c(NA,"ROOSTER","FEATHER","LIGHT FEATHER", "LIGHT","MIDDLE","MEDIUM HEAVY","HEAVY","SUPER HEAVY","ULTRA HEAVY")
dt_Absolute_Results[, Weight_Class := factor(Weight_Class, levels = Factor_Order)]
ggplot(dt_Absolute_Results, aes(x = Weight_Class)) +
  geom_bar(fill = "orange", color = "black") +
  labs(title = "Weight Class Distribution",
       x = "Weight Class",
       y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
